version: "3.3"

services:
  text-generation-webui:
    image: text-generation-webui
    environment:
      - CLI_ARGS=--gptq-bits 4 --gpu-memory 8 --listen --no-stream --listen-port 7861
    security_opt:
      - label=type:nvidia_container_t
    ports:
      - "7861:7861"
    stdin_open: true
    tty: true
    volumes:
      - /path/to/models:/data:z
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
